/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminCompanies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAppOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelAppOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/orders/{orderId}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refundAppOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/customers/{customerId}/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAppCustomerWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loyalty/accounts/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLoyaltyAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStockMovements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        Company: {
            /** Format: uuid */
            id: string;
            name: string;
            active: boolean;
        };
        Product: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            companyId: string;
            name: string;
            /** Format: decimal */
            salePrice?: string | null;
            taxType: components["schemas"]["TaxType"];
            unitType: components["schemas"]["ProductUnitType"];
            active: boolean;
        };
        CreateOrderRequest: {
            /** Format: uuid */
            companyId: string;
            /** Format: uuid */
            posId: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            customerId?: string | null;
            shippingType: components["schemas"]["ShippingType"];
            /** Format: date-time */
            orderTime: string;
            idempotencyKey?: string | null;
            lines: components["schemas"]["OrderLine"][];
            payments: components["schemas"]["OrderPayment"][];
        };
        Order: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            companyId: string;
            /** Format: decimal */
            total: string;
            state: components["schemas"]["OrderState"];
            /** Format: date-time */
            orderTime: string;
            payments: components["schemas"]["OrderPayment"][];
        };
        OrderLine: {
            /** Format: uuid */
            productId: string;
            quantity: number;
        };
        OrderPayment: {
            paymentType: components["schemas"]["PaymentType"];
            /** Format: decimal */
            amount: string;
            /** @default TRY */
            currency: string;
            externalReference?: string | null;
        };
        OrderResponse: {
            /** Format: uuid */
            orderId: string;
            idempotencyKey: string;
            /** Format: decimal */
            total: string;
            paymentSummary: components["schemas"]["PaymentSummary"];
            existing: boolean;
        };
        ReasonRequest: {
            /** Format: uuid */
            companyId: string;
            /** Format: uuid */
            userId: string;
            reason: string;
        };
        CancelOrderResponse: {
            /** Format: uuid */
            orderId: string;
            orderState: components["schemas"]["OrderState"];
            existing: boolean;
        };
        WalletAccount: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            customerId: string;
            currency: string;
            /** Format: decimal */
            balance: string;
        };
        LoyaltyAccount: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            customerId: string;
            tierName?: string | null;
            pointBalance: number;
        };
        StockMovement: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            companyId: string;
            /** Format: uuid */
            storeId: string;
            /** Format: uuid */
            productId: string;
            movementType: components["schemas"]["StoreProductMovementType"];
            /** @enum {string} */
            direction: "Debit" | "Credit";
            quantity: number;
            /** Format: date-time */
            occurredAt: string;
        };
        /** @enum {string} */
        PaymentType: "Cash" | "CreditCard" | "Ticket" | "Sodexo" | "Multinet";
        /** @enum {string} */
        PaymentSummary: "Cash" | "CreditCard" | "Ticket" | "Sodexo" | "Multinet" | "Mixed";
        /** @enum {string} */
        ShippingType: "Self" | "ComeTake" | "Order" | "Customer";
        /** @enum {string} */
        OrderState: "Received" | "Preparing" | "Completed" | "Cancelled" | "Deleted" | "Transferring";
        /** @enum {string} */
        ProductUnitType: "Adet" | "MiliLitre" | "Gram";
        /** @enum {string} */
        StoreProductMovementType: "StockIn" | "StockOut" | "Destroy" | "Order" | "Purchase" | "TransferIn" | "TransferOut";
        /** @enum {string} */
        TaxType: "Bir" | "Sekiz" | "OnSekiz";
    };
    responses: {
        /** @description ProblemDetails error response */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        CompanyId: string;
        CustomerId: string;
        OrderId: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAdminCompanies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Company list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listAdminProducts: {
        parameters: {
            query: {
                companyId: components["parameters"]["CompanyId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createAppOrder: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Existing idempotent order result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Order created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    cancelAppOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description Order cancelled with ledger reversal rows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelOrderResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    refundAppOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description Order refunded with ledger reversal rows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelOrderResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAppCustomerWallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wallet account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletAccount"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getLoyaltyAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: components["parameters"]["CustomerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loyalty account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoyaltyAccount"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listStockMovements: {
        parameters: {
            query: {
                companyId: components["parameters"]["CompanyId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stock movement list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMovement"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
